{{- if and (.Capabilities.APIVersions.Has "opentelemetry.io/v1alpha1/Instrumentation") .Values.opentelemetry.endpoint }}
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  exporter:
    endpoint: {{ .Values.opentelemetry.endpoint }}
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
{{- end }}
